apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: data-pv
  accessModes:
    - ReadWriteMany
